[package]
name = "libp2p-x509"
version = "0.18.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "X.509 generation and verification for libp2p"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking", "tls", "x509"]
categories = ["network-programming", "asynchronous"]

[dependencies]
libp2p-core = { path = "../../core", version = "0.18.0" }
log = "0.4.8"
rcgen = { version = "0.7.0", default-features = false }
ring = "0.16.11"
rustls = { version = "0.17.0", features = ["dangerous_configuration"] }
thiserror = "1.0.15"
untrusted = "0.7.0"
webpki = "0.21.2"
yasna = "0.3.1"

[dependencies.x509]
package = "x509-signature"
version = "0.3.0"
features = ["webpki", "rustls", "std"]
