[package]
name = "libp2p-wasm-ext"
version = "0.6.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
description = "Allows passing in an external transport in a WASM environment"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = "0.1.29"
js-sys = "0.3.32"
libp2p-core = { version = "0.13.0", path = "../../core" }
parity-send-wrapper = "0.1.0"
tokio-io = "0.1.12"
wasm-bindgen = "0.2.55"
wasm-bindgen-futures = "0.3.27"
