[package]
name = "libp2p-quic"
version = "0.17.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "MIT"
description = "A libp2p transport using QUIC"
keywords = ["peer-to-peer", "libp2p", "quic", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-macros = "2.0.0"
async-std = "1.5.0"
either = "1.5.3"
env_logger = "0.7.1"
err-derive = "0.2.2"
futures = "0.3.4"
futures-timer = "3.0.2"
ipnet = "2.2.0"
libp2p-core = { path = "../../core", version = "0.17.1" }
log = "0.4.8"
parking_lot = "0.10.0"
protobuf = "2.10.1"
quinn-proto = "0.6.0"
rcgen = { version = "0.7.0", default_features = false }
ring = "0.16.11"
rustls = { version = "0.17.0", features = ["dangerous_configuration"] }
tracing = { version = "0.1.12", optional = true }
tracing-core = { version = "0.1.10", optional = true }
tracing-subscriber = { version = "0.2.1", optional = true }
untrusted = "0.7.0"
webpki = "0.21.2"
x509 = { path = "../../misc/x509", package = "libp2p-x509", version = "0.17.1" }
yasna = { version = "0.3.1" }

[features]
trace = [
  "tracing-subscriber",
  "tracing",
  "tracing-core",
]
