# Copyright 2017-2018 Parity Technologies (UK) Ltd.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
[package]
name = "libp2p-quic"
version = "0.13.2"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quinn-proto = "0.4.0"
rustls = { version = "0.16.0", features = ["dangerous_configuration"] }
libp2p-core = { path = "../../core", version = "0.13.1" }
log = "0.4.8"
quinn = { git = "https://github.com/daxpedda/quinn.git", rev = "750081f2fcc431e9d7597c387b3d3b62a2a2cbb7" }
tokio = { version = "0.2.2", features = ["rt-threaded"] }
ipnet = "2.1.0"
err-derive = "0.2.1"
futures = { version = "0.3.1", package = "futures", features = ["compat"] }
futures-core = "0.3.1"
